### ISSUE TITLE
cargo based Wrangler v1 is deprecated

### ISSUE THREAD

**Issue by ghost** [redirectionio/cloudflare-worker#1]
I just noticed this again during a publish of the worker.

```
wrangler publish
DEPRECATED 
The version of Wrangler you are using is now deprecated.
Please update to the latest version of wrangler to prevent critical errors.
If originally installed via npm, run `npm uninstall -g @cloudflare/wrangler && npm install -g wrangler` to update to the latest version.
If originally installed via cargo, run `cargo uninstall wrangler && npm install -g wrangler`
Docs migration guide: https://developers.cloudflare.com/workers/wrangler/migration/migrating-from-wrangler-1/#update-wrangler-version
```

Cloudflare also has send out an email in February informing about deprecating Wrangler v1 as of February 16, 2023. They will maintain support for critical updates through August 1, 2023 at which point all support for v1 will be sunsetted. Could you please provide an updated version of the worker?

Thank you and best regards,
Daniel

**Comment by joelwurtz** [comment]
Last version (2.6.0) is now on wrangler 2 with a pure rust worker (no more js) we are doing final tests to ensure there is no problem before making it available on our manager

**Comment by ghost** [comment]
Thank you. I will take a look at that code.
