### ISSUE TITLE
`redirectionio` dependency declaration is a path

### ISSUE THREAD

**Issue by ptondereau** [redirectionio/cloudflare-worker#3]
Is this intended to have a path at: 
https://github.com/redirectionio/cloudflare-worker/blob/b8360c1e6025869476a5ec2f235af59dce621d43/Cargo.toml#L13

Instead of relying on the crates.io published version?

**Comment by joelwurtz** [comment]
We have both as we build it from our monorepository and version will be used if path is not present

**Comment by joelwurtz** [comment]
Was wrong, this is an error, in fact it keep the version property only when it's published on crates, was thinking it would do the same here, will fix this soon

**Comment by xavierlacot** [comment]
Thanks a lot @ptondereau :tada: 
fixed in 8487f7c233ab1e2f1c92a7275c8fd4b6735186ab
